declare const classNames: {
  readonly layout: "layout";
  readonly sider: "sider";
  readonly "deck-select-container": "deck-select-container";
  readonly content: "content";
  readonly deck: "deck";
  readonly select: "select";
  readonly "select-btns": "select-btns";
  readonly editorColumns: "editorColumns";
  readonly container: "container";
  readonly title: "title";
  readonly "deck-zone": "deck-zone";
  readonly "search-cards-container": "search-cards-container";
  readonly "search-count": "search-count";
  readonly "editing-zone-name": "editing-zone-name";
  readonly mobileTabs: "mobileTabs";
  readonly scrollHost: "scrollHost";
  readonly detailHost: "detailHost";
  readonly deckName: "deckName";
  readonly editorActions: "editorActions";
  readonly "ant-input-affix-wrapper": "ant-input-affix-wrapper";
};
export = classNames;
